### ISSUE TITLE
能否删除里面的一个标识

### ISSUE THREAD

**Issue by fenggolang** [bingoohuang/snmp#1]
<img width="1506" alt="image" src="https://github.com/bingoohuang/snmp/assets/16982786/0b0e26b9-4d99-4f33-a749-ce4d89118401">

**Comment by bingoohuang** [comment]
what, why?

**Comment by fenggolang** [comment]
因为包含了我所在公司的标识。

**Comment by fenggolang** [comment]
> what, why?
因为包含了我所在公司的标识

**Comment by bingoohuang** [comment]
changed!
